development: &dev
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hue_dev
  pool: 5
  username: root
  password: root

test:
  <<: *dev
  database: hue_test

production:
  <<: *dev
  database: hue_prod
